MVC_MassageBoard/Models/Model1.cs
namespace MVC_MassageBoard.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class Model1 : DbContext
    {
        public Model1()
            : base("name=Model1")
        {
        }

        public DbSet<Testtb> Testtables { get; set; }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    }
}

MVC_MassageBoard/Models/Testtb.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.ComponentModel;

namespace MVC_MassageBoard.Models
{
    public class Testtb
    {
        // 代碼
        [Key]
        [DisplayName("留言代碼")]
        public string user { get; set; }

        // 標題
        [Required]
        [DisplayName("標題")]
        public string title { get; set; }

        // 內容
        [Required]
        [DisplayName("內容")]
        public string commet { get; set; }

        // 日期
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode =true)]
        [DisplayName("日期")]
        public DateTime date { get; set; }
    }
}

MVC_MassageBoard/Controllers/TesttbsController.cs
using System;

using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_MassageBoard.Models;

namespace MVC_MassageBoard.Controllers
{
    public class TesttbsController : Controller
    {
        private Model1 db = new Model1();

        // GET: Testtbs
        public ActionResult Index(string searchString)
        {
            var msg = from m in db.Testtables select m;
            if(!String.IsNullOrEmpty(searchString))
            {
                msg = msg.Where(s => (s.title.Contains(searchString))? (s.title.Contains(searchString)):((s.commet.Contains(searchString))? (s.commet.Contains(searchString)):(s.user.Contains(searchString))));
            }
            return View(msg);
        }

        // GET: Testtbs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Testtb testtb = db.Testtables.Find(id);
            if (testtb == null)
            {
                return HttpNotFound();
            }
            return View(testtb);
        }

        // GET: Testtbs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Testtbs/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "user,title,commet,date")] Testtb testtb)
        {
            if (ModelState.IsValid)
            {
                db.Testtables.Add(testtb);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(testtb);
        }

        // GET: Testtbs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Testtb testtb = db.Testtables.Find(id);
            if (testtb == null)
            {
                return HttpNotFound();
            }
            return View(testtb);
        }

        // POST: Testtbs/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "user,title,commet,date")] Testtb testtb)
        {
            if (ModelState.IsValid)
            {
                db.Entry(testtb).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(testtb);
        }

        // GET: Testtbs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Testtb testtb = db.Testtables.Find(id);
            if (testtb == null)
            {
                return HttpNotFound();
            }
            return View(testtb);
        }

        // POST: Testtbs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Testtb testtb = db.Testtables.Find(id);
            db.Testtables.Remove(testtb);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_MassageBoard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="~/scripts/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" src="~/scripts/moment.min.js"></script>
    <script type="text/javascript" src="~/scripts/bootstrap-datetimepicker.js"></script>
    <link rel="stylesheet" href="~/Content/bootstrap-datetimepicker.css" />
    <!-- Title -->
    <title>Samuel's Massage Board</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")

    <style>
        /* 設定 body 背景顏色 */
        body {
            background-color: rgb(226,205,188) !important;
            /* 使用莫蘭迪色系 rgb(226,205,188) */
        }

        /* 設定 navbar 背景顏色 */
        .navbar {
            background-color: rgb(160,106,80) !important;
            /* 使用莫蘭迪色系 rgb(160,106,80) */
        }

            /* 設定 navbar 最左邊標題的顏色、大小、粗體 */
            .navbar .navbar-brand {
                color: #fff !important;
                font-size: 24px;
                font-weight: bold;
                /* 顏色:白色、大小:24pixel、粗細:粗體 */
            }

        /* 設定 jumbotron 背景顏色、文字顏色、大小、粗體*/
        .alert-warning {
            background-color: rgb(188,169,162) !important;
            /* 背景使用莫蘭迪色系 rgb(188,169,162) */
            color: #fff !important;
            font-weight: bold;
            font-size: 50px;
            /* 文字顏色:白色、大小:50pixel、粗細:粗體 */
        }

        /* 表格頭部背景顏色、文字顏色、文字置中 */
        .table th {
            background-color: rgb(49,36,28) !important;
            color: #fff !important;
            text-align: center;
        }
    </style>
    <script type="text/javascript">
        /* 呼叫 datetimepicker */
        $(function () {
            $('#datepicker').datetimepicker({
                format: "YYYY/MM/DD"
            });
        });
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <!-- navbar 最左邊標題 -->
                @Html.ActionLink("Samuel's Massage Board", "Index", "Testtbs", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer style="width:100%; height: 20px; position:relative; bottom:0px; left:0%">
            <!-- footer copyright -->
            <a href="https://github.com/Samuelchi861008/MVC_Web-MassageBoard" target="_blank" style="text-decoration:none;"><font color="#fcfcfc" size="1">Copyright &copy; 2019 Samuel Chi All rights reserved.</font></a>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

MVC_MassageBoard/Views/Testtbs/Create.cshtml
@model MVC_MassageBoard.Models.Testtb

@{
    ViewBag.Title = "新增";
}

<h2><b>@ViewBag.Title</b></h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.user, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.user, new { htmlAttributes = new { @class = "form-control", @placeholder = "請給予此留言專屬的代碼"} })
            @Html.ValidationMessageFor(model => model.user, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control", @placeholder = "留言標題" } })
            @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.commet, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.commet, new { @class = "form-control", @rows = 10, @placeholder = "留言內容" })
            @Html.ValidationMessageFor(model => model.commet, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.date, new { @class = "form-control", @id = "datepicker", @placeholder = "選擇日期" })
            @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" value="新增" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span> 新增
            </button>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink(" 回首頁", "Index", null, new { @class = "glyphicon glyphicon-home btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_MassageBoard/Views/Testtbs/Delete.cshtml
@model MVC_MassageBoard.Models.Testtb

@{
    ViewBag.Title = "刪除";
}

<h2><b>@ViewBag.Title</b></h2>

<h5><b>確定想要刪除此訊息嗎 ? </b></h5>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.commet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.commet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <button type="submit" value="刪除" class="btn btn-danger">
            <span class="glyphicon glyphicon-trash"></span> 刪除
        </button>
        @Html.ActionLink(" 回首頁", "Index", null, new { @class = "glyphicon glyphicon-home btn btn-info" })
    </div>
    }
</div>

MVC_MassageBoard/Views/Testtbs/Details.cshtml
@model MVC_MassageBoard.Models.Testtb

@{
    ViewBag.Title = "查看";
}

<h2><b>@ViewBag.Title</b></h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.commet)
        </dt>
        
        <dd>
            @Html.DisplayFor(model => model.commet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(" 編輯", "Edit", new { id = Model.user }, new { @class = "glyphicon glyphicon-pencil btn btn-success" })
    @Html.ActionLink(" 回首頁", "Index", null, new { @class = "glyphicon glyphicon-home btn btn-info" })
</p>

MVC_MassageBoard/Views/Testtbs/Edit.cshtml
@model MVC_MassageBoard.Models.Testtb

@{
    ViewBag.Title = "編輯";
}

<h2><b>@ViewBag.Title</b></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.user)

    <div class="form-group">
        @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.commet, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.commet, new { @class = "form-control", @rows = 10})
            @Html.ValidationMessageFor(model => model.commet, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.date, new { @class = "form-control", @id = "datepicker", Value = String.Format("{0:yyyy-MM-dd}", Model.date)})
            @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-floppy-disk"></span> 儲存
            </button>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink(" 回首頁", "Index", null, new { @class = "glyphicon glyphicon-home btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_MassageBoard/Views/Testtbs/Index.cshtml
@model IEnumerable<MVC_MassageBoard.Models.Testtb>

@{
    ViewBag.Title = "留言板";
}

<!-- 上方 jumbotron -->
<div class="jumbotron alert-warning">
    @ViewBag.Title
</div>

<!-- 搜尋 -->
<p>
    @using (Html.BeginForm())
    {
        <p>
            @Html.TextBox("searchString", null, new { @class = "form-control", @placeholder = "留言代碼、標題、內容", @style = "display:inline" })
            <button type="submit" class="btn btn-primary" style="display:inline" id="searchBtn">
                <span class="glyphicon glyphicon-search"></span> 搜尋
            </button>
        </p>
    }
</p>

<!-- 留言列表 -->
<table class="table table-hover table-bordered">
    <tr>
        <th>
            <div class="glyphicon glyphicon-pushpin"></div>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            <div class="glyphicon glyphicon-list"></div>
            @Html.DisplayNameFor(model => model.commet)
        </th>
        <th>
            <div class="glyphicon glyphicon-calendar"></div>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.commet)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        <td align="center">
            @Html.ActionLink(" 編輯", "Edit", new { id = item.user}, new {@class = "glyphicon glyphicon-pencil btn btn-success" })
            @Html.ActionLink(" 查看", "Details", new { id = item.user }, new { @class = "glyphicon glyphicon-eye-open btn btn-warning" })
            @Html.ActionLink(" 刪除", "Delete", new { id = item.user }, new { @class = "glyphicon glyphicon-trash btn btn-danger" })
        </td>
    </tr>
}

</table>

<!-- 新增留言 Button -->
<p>
    @Html.ActionLink(" 新增留言", "Create", null , new { @class = "glyphicon glyphicon-plus btn btn-info" })
</p>